//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classigoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MsgId { get; set; }
        public System.Guid FromUserId { get; set; }
        public System.Guid ToUserId { get; set; }
        public int AdId { get; set; }
        public string Message1 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<bool> IsRed { get; set; }
    
        public virtual Add Add { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
